<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Profile</name>
   <tag></tag>
   <elementGuidId>6e591b74-4a0f-4a8c-97e3-6da2b8bcbd92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;https\:\/\/gipm\.destroidmous\.my\.id\/profile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'https://gipm.destroidmous.my.id/profile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a76376f-4d83-4e38-afea-9e15d7766330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full px-4 py-2 text-start text-sm leading-5 text-gray-900 transition duration-300 ease-in-out hover:bg-gray-100 focus:bg-gray-100 focus:outline-none </value>
      <webElementGuid>29a95294-65ce-414b-af3f-f51593a80fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gipm.destroidmous.my.id/profile</value>
      <webElementGuid>5b5e276b-8e04-47e2-a5f6-6c8434278e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Profile</value>
      <webElementGuid>117c2bea-52ac-4999-92e5-e4e56a5a3bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a89218fc5466fb71568b8f3e5fdd3123</value>
      <webElementGuid>3b1a2c8b-c707-47bb-8a14-1616f86a8425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/profile']</value>
      <webElementGuid>929380dc-3435-4297-a666-38f2eda6dfeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/profile']</value>
      <webElementGuid>c644a9bd-77c7-4368-a616-32e5e09b8bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gipm.destroidmous.my.id/profile' and (text() = 'Profile' or . = 'Profile')]</value>
      <webElementGuid>483796e8-84d6-404d-8455-1b925a148f7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
