<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Projects</name>
   <tag></tag>
   <elementGuidId>288570a4-7ee6-491f-a878-2cf684a4b2fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'https://gipm.destroidmous.my.id/projects']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;https\:\/\/gipm\.destroidmous\.my\.id\/projects&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Projects&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4091931-f1c3-4098-b4dd-701615fe1fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center text-sm font-regular leading-5 transition duration-300 ease-in-out focus:outline-none text-gray-500 hover:text-gray-800 focus:text-gray-700flex items-center justify-between w-full pt-1 pb-1 text-sm rounded-sm 
                    text-gray-500 hover:text-gray-800 hover:bg-gray-200</value>
      <webElementGuid>5796a292-5a0b-4ccf-88ac-01df7b3483b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gipm.destroidmous.my.id/projects</value>
      <webElementGuid>0f40143a-d4fe-4d9e-aecb-84f2cf671c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projects</value>
      <webElementGuid>a10fddeb-8c96-413f-857b-a9eb90c8fdcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bf320ee156942ef2f083c52800abf527</value>
      <webElementGuid>c8fc454b-8187-45db-ac36-ecec1886508f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/projects']</value>
      <webElementGuid>28cb83f9-838e-4839-8c3e-33eb053135b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/projects']</value>
      <webElementGuid>4be1a289-f7e5-4b5c-a127-fd20a486deab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://gipm.destroidmous.my.id/projects' and (text() = 'Projects' or . = 'Projects')]</value>
      <webElementGuid>2e02752e-a1ef-4476-94d7-f3f46c7b739c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
