analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3472297,"name"\:"First Project","teamId"\:3457506,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3494068,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3457506,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
