<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>b542912c-3031-4583-b6af-159b9b346eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form .text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Simpan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c605b82-be33-4205-b77b-d34ef98d87f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-blue-600 text-white px-4 py-2 rounded</value>
      <webElementGuid>f7986146-7980-4348-8d9a-266a142b6655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>3f252a05-bdb6-4bd8-8877-c9f8260622c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e032ad3d092f2f89e1afa053b8dc8f97</value>
      <webElementGuid>ea0227ba-32ea-4eea-9435-325fdad5d7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>9e1d9015-8b10-47d5-bfec-e73034d37cd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>ffe27e2d-e1a3-42bc-b108-70539b46fb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>0f4069d7-189a-41e8-b2c4-97cbe325b33b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
