<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Role -clientdeveloperproject manage</name>
   <tag></tag>
   <elementGuidId>ba8b81bf-34a4-4eab-8cc2-b918ad5dfba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4337ba6-3b46-464d-9e56-3f43f4cea673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border p-2 w-full rounded</value>
      <webElementGuid>b3025986-16d6-4e53-bf19-ac61b3e06b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Pilih Role --clientdeveloperproject manager</value>
      <webElementGuid>7bb80134-59e3-4335-ae10-c68b9ab85756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b83b0f05aca55bb078d925bdbdb92fe3</value>
      <webElementGuid>0ca89a9b-5d16-4037-a228-97fc2af03b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fc625433-b3b4-4044-9505-b99207c321e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>01ae96d6-2322-415e-ae42-9a74362e6941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = '-- Pilih Role --clientdeveloperproject manager' or . = '-- Pilih Role --clientdeveloperproject manager')]</value>
      <webElementGuid>722bdaa0-97c2-4b33-b0b3-c632ca69913f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
