<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contracts</name>
   <tag></tag>
   <elementGuidId>9cfe2f07-618e-473d-90d4-3801b8c6d960</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;https\:\/\/gipm\.destroidmous\.my\.id\/contracts&quot;] span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Contracts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>719b2481-06ca-4e0a-b194-95342a87ca90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contracts</value>
      <webElementGuid>3d3dbafb-c60c-4be0-b910-ac73a9782247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b226ec8010e2efb4b290b8c03a38926d</value>
      <webElementGuid>c7ef5b24-9791-4691-a105-d81fa5bc19ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      <webElementGuid>5961e34e-2506-4dab-b096-713f766eae8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      <webElementGuid>c70b2688-e35e-49b8-b8b3-d1a507dc3847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contracts' or . = 'Contracts')]</value>
      <webElementGuid>d79545b2-16bc-456e-9444-b97855928f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
