<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>4fee03c7-012c-4e7f-abe8-024611548d1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>517e4cd8-e885-4101-b63c-19135f73e48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>13ae40b4-d6ac-47ca-b448-00eb47880bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f1711f8e-0eb7-4355-9934-e9171cae2351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>60774aaf-36d6-4bae-b9e2-20f108ab9d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>779d5b12-351b-425a-a781-2b7f79dd0938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>
                w-full rounded-md border-gray-300 shadow-sm 
                focus:border-[#db2727] focus:ring-[#db2727]
                py-3 px-3 
                py-3 px-3 pe-10mt-1 block w-3/4
            </value>
      <webElementGuid>761d2fc9-69e3-4918-bc39-7564131827c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c7773a9b427696d13ef2c51a10771732</value>
      <webElementGuid>1d77df54-1ebf-4b45-9a3d-71b57d19c923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'password']</value>
      <webElementGuid>c1f837f4-eda9-47c5-916f-94c53186cc43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'password']</value>
      <webElementGuid>92535847-9616-4f88-9cfb-d7f6e3f946b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'password' and @name = 'password' and @placeholder = 'Password' and @type = 'password']</value>
      <webElementGuid>f94fbc52-5d9d-4b69-b4b9-e809464cc800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
