<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>8a9e62de-7e5e-41be-a25f-10cfbb56d9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form .text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Update&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdb2df4a-85b6-4cc3-bd3e-8a7a97a9c5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-blue-600 text-white px-4 py-2 rounded</value>
      <webElementGuid>d4b47f48-41d2-4a1d-af9d-a963cc4eeec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>290bdfbc-54e4-41fe-8bbe-c70ca36b438c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e032ad3d092f2f89e1afa053b8dc8f97</value>
      <webElementGuid>21263fee-f736-47cc-95e2-ba8a2fdb32b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>f27ef4a2-03db-4362-8b50-90356c794d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>2290150f-ac9c-4324-bb21-7f8477136257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>c894cb39-971c-4edd-a93c-2738c0e2f372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
