<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama</name>
   <tag></tag>
   <elementGuidId>3575ad68-6c84-40b3-9e5d-652deae46eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;UserTest&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'UserTest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nama&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01dcb2ac-1652-486e-ba67-384638aebfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05b1e2bf-62e6-46b1-bdc3-038e0a901afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama</value>
      <webElementGuid>ec4bdcfd-9e35-4144-81e5-3003b2a4f0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border p-2 w-full rounded</value>
      <webElementGuid>5a58bd37-a9c5-4557-992d-9f507dd74c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UserTest</value>
      <webElementGuid>bcd694fa-78f0-42a7-8883-c280f5686304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-534297a3b4b439a64da0994f31207dd7</value>
      <webElementGuid>e105a297-18ca-48a3-9ca0-e462ab5991e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'UserTest']</value>
      <webElementGuid>7ca65b10-7e7f-4506-844e-3ea7147d4043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'UserTest']</value>
      <webElementGuid>5fe6ae77-360d-4a70-ac96-51ee364c914f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nama']</value>
      <webElementGuid>6666137a-9602-405c-b98b-cfe0e2fa660a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
