<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rfd-hidden-text-_re_-hidden-text-_rf</name>
   <tag></tag>
   <elementGuidId>9da5a6a5-8d71-4c2a-9e4c-96fac25c1da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-rfd-droppable-id = 'done']//*[@aria-describedby = 'rfd-hidden-text-:re:-hidden-text-:rf:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-rfd-droppable-id=&quot;done&quot;] [aria-describedby=&quot;rfd-hidden-text-\:re\:-hidden-text-\:rf\:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e6e36b3-2b06-495c-9a42-be2cf7b56dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rfd-draggable-context-id</name>
      <type>Main</type>
      <value>:re:</value>
      <webElementGuid>d090dc2a-73ed-4aba-a9d6-fc095b45c4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rfd-draggable-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>eb4c0d64-9800-4647-ab49-5e5aa9c46c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>238c0959-37e2-4f62-a844-ee68644441ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8db1892-8183-4394-b579-c9ac25fae539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>rfd-hidden-text-:re:-hidden-text-:rf:</value>
      <webElementGuid>da64c357-7bfe-49eb-88ec-d09857fbb39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rfd-drag-handle-draggable-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7063ba28-328c-4031-847f-b2489c4fd978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rfd-drag-handle-context-id</name>
      <type>Main</type>
      <value>:re:</value>
      <webElementGuid>e68126d7-132b-44ea-b6f3-7e0ad5ed4659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db56af56-b7b5-4b53-bc16-94ed29bfded1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white p-4 rounded-lg shadow-sm border border-gray-200 mb-3 hover:shadow-md transition-shadow group</value>
      <webElementGuid>4a2a4028-506c-4aa5-a4e2-5e811a9188bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>baselineganti passwordSee Detail →</value>
      <webElementGuid>9c4f1d25-756f-456e-8740-013d89828651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-152070d787327e3a6b134421dd28e35f</value>
      <webElementGuid>149c257e-e2be-4749-a200-3554e7ca9b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-rfd-droppable-id = 'done']//*[@aria-describedby = 'rfd-hidden-text-:re:-hidden-text-:rf:']</value>
      <webElementGuid>413374d5-1ab4-418f-84e3-f33e25c57692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-rfd-droppable-id = 'done']//*[@aria-describedby = 'rfd-hidden-text-:re:-hidden-text-:rf:']</value>
      <webElementGuid>9f3c8cde-5145-4cc7-abec-6b17c96d6d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'baselineganti passwordSee Detail →' or . = 'baselineganti passwordSee Detail →')]</value>
      <webElementGuid>47c69154-20de-4b55-bd26-61f9fc685b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
