<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contracts</name>
   <tag></tag>
   <elementGuidId>8c765219-3d8b-49ad-9b29-a3d21120a611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;https\:\/\/gipm\.destroidmous\.my\.id\/contracts&quot;] span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Contracts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54e8cb22-3109-45e4-a987-5b0aa0765a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contracts</value>
      <webElementGuid>16538c7b-cb5c-4f59-9eae-8fcbba2aedee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b226ec8010e2efb4b290b8c03a38926d</value>
      <webElementGuid>018f7173-9dde-4a31-9618-6cd366eb2d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      <webElementGuid>4b85549e-aac7-4e9a-a871-0ba941200a86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'https://gipm.destroidmous.my.id/contracts']//span</value>
      <webElementGuid>4b134d52-baeb-459e-9490-5392e25a290d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Contracts' or . = 'Contracts')]</value>
      <webElementGuid>8ce7651d-dc4e-47ec-bb50-00694620c485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
